routes/web.php
<?php

use App\Http\Controllers\Admin\InvoiceController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\User\AccountController;
use App\Http\Controllers\User\DashboardController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;
use App\Http\Livewire\Admin\Seo\Edit as SeoEdit;
use App\Http\Livewire\Admin\Blog\Edit as BlogEdit;
use App\Http\Livewire\Admin\Page\Edit as EditPage;
use App\Http\Livewire\Admin\Seo\Index as SeoIndex;
use App\Http\Livewire\Admin\User\Edit as EditUser;
use App\Http\Livewire\Admin\Blog\Index as BlogIndex;
use App\Http\Livewire\Admin\Page\Index as PageIndex;
use App\Http\Livewire\Admin\Seo\Create as SeoCreate;
use App\Http\Livewire\Admin\User\Index as UserIndex;
use App\Http\Livewire\Admin\Blog\Create as BlogCreate;
use App\Http\Livewire\Admin\Category\Index as CategoryIndex;
use App\Http\Livewire\Admin\Category\Create as CategoryCreate;
use App\Http\Livewire\Admin\Category\Edit as CategoryEdit;
use App\Http\Livewire\Admin\Page\Create as PageCreate;
use App\Http\Livewire\Admin\User\Create as UserCreate;
use App\Http\Livewire\Admin\Getway\Edit as GatewayEdit;
use App\Http\Livewire\Admin\Getway\Index as GatewayIndex;
use App\Http\Livewire\Admin\Settings\Hero as HeroSettings;
use App\Http\Livewire\Admin\Getway\Create as GatewayCreate;
use App\Http\Livewire\Admin\Settings\Index as SettingsIndex;
use App\Http\Livewire\Admin\Lang\Create as LangCreate;
use App\Http\Livewire\Admin\Lang\Customize as LangCustomize;
use App\Http\Livewire\Admin\Lang\Edit as LangEdit;
use App\Http\Livewire\Admin\Lang\Index as LangIndex;
use App\Http\Livewire\Admin\Menu\Builder as MenuBuilder;
use App\Http\Livewire\Admin\Menu\Create as MenuCreate;
use App\Http\Livewire\Admin\Menu\Edit as MenuEdit;
use App\Http\Livewire\Admin\Menu\Index as MenuIndex;
use App\Http\Livewire\Admin\Settings\Footer as FooterSettings;
use App\Http\Livewire\Admin\Transcation\Index as TranscationIndex;
use App\Http\Livewire\Admin\Settings\Profile\Index as SettingsProfileIndex;
use App\Http\Controllers\Admin\MenuOrderController;
use App\Http\Controllers\Auth\SocialiteController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\ChatbotShowController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PricingController;
use App\Http\Controllers\PrivacyController;
use App\Http\Controllers\User\AiChatsController;
use App\Http\Controllers\User\AiCodeController;
use App\Http\Controllers\User\AiImageController;
use App\Http\Controllers\User\AiSpeechToTextController;
use App\Http\Controllers\User\BillingController;
use App\Http\Controllers\User\DocumentController;
use App\Http\Controllers\User\PlanController;
use App\Http\Controllers\User\SettingsController;
use App\Http\Controllers\User\StripeController;
use App\Http\Controllers\User\SupportController;
use App\Http\Controllers\User\TemplatesController;
use App\Http\Livewire\Admin\Dashboard;
use App\Http\Livewire\Admin\Plan\Create as PlanCreate;
use App\Http\Livewire\Admin\Plan\Edit as PlanEdit;
use App\Http\Livewire\Admin\Plan\Index as PlanIndex;
use App\Http\Livewire\Admin\Settings\Affilate;
use App\Http\Livewire\Admin\Settings\Testimonial\Create as testimonialCreate;
use App\Http\Livewire\Admin\Settings\Testimonial\Edit as testimonialEdit;
use App\Http\Livewire\Admin\Settings\Testimonial\Index as testimonialIndex;
use App\Http\Livewire\Admin\Settings\Features\Create as FeaturesCreate;
use App\Http\Livewire\Admin\Settings\Features\Edit as FeaturesEdit;
use App\Http\Livewire\Admin\Settings\Features\Index as FeaturesIndex;
use App\Http\Livewire\Admin\Settings\Faq\Index as FAQIndex;
use App\Http\Livewire\Admin\Settings\Faq\Create as FAQCreate;
use App\Http\Livewire\Admin\Settings\Faq\Edit as FAQEdit;
use App\Http\Livewire\Admin\Settings\General;
use App\Http\Livewire\Admin\Settings\Invoice;
use App\Http\Livewire\Admin\Settings\OpenAi;
use App\Http\Livewire\Admin\Settings\PrivacyPolicy;
use App\Http\Livewire\Admin\Settings\Smtp;
use App\Http\Livewire\Admin\Settings\System\Index as SystemIndex;
use App\Http\Livewire\Admin\Support\Index as SupportIndex;
use App\Http\Livewire\Admin\Support\View as SupportView;
use App\Http\Livewire\Auth\Login;
use App\Http\Livewire\Admin\Emailtemplate\Edit as EmailTemplateEdit;
use App\Http\Livewire\Admin\Emailtemplate\Index as EmailTemplateIndex;
use App\Http\Livewire\Admin\Templates\BuildIn\Index as BuildInTemplatesIndex;
use App\Http\Livewire\Admin\Templates\BuildIn\Edit as BuildInTemplatesEdit;
use App\Http\Livewire\Admin\Templates\Category\Index as TemplatesCategoryIndex;
use App\Http\Livewire\Admin\Templates\Category\Create as TemplatesCategoryCreate;
use App\Http\Livewire\Admin\Templates\Category\Edit as TemplatesCategoryEdit;
use App\Http\Livewire\Admin\Templates\Chat\Create as ChatTemplatesCreate;
use App\Http\Livewire\Admin\Templates\Chat\Edit as ChatTemplatesEdit;
use App\Http\Livewire\Admin\Templates\Chat\Index as ChatTemplatesIndex;
use App\Http\Livewire\Admin\Templates\Custom\Index as CustomTemplatesIndex;
use App\Http\Livewire\Admin\Templates\Custom\Create as CustomTemplatesCreate;
use App\Http\Livewire\Admin\Templates\Custom\Edit as CustomTemplatesEdit;
use App\Http\Middleware\VerifyCsrfToken;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('admin/menu/order', [MenuOrderController::class, 'order'])->name('admin.menu.order');
/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('dashboard', Dashboard::class)->name('dashboard');

    // Built-in Templates
    Route::get('templates/all', BuildInTemplatesIndex::class)->name('buildin.templates');
    Route::get('templates/build-in/{id}/edit', BuildInTemplatesEdit::class)->name('buildin.templates.edit');

    // Custom Templates
    Route::get('templates/custom', CustomTemplatesIndex::class)->name('custom.templates');
    Route::get('templates/custom/create', CustomTemplatesCreate::class)->name('custom.templates.create');
    Route::get('templates/custom/{id}/edit', CustomTemplatesEdit::class)->name('custom.templates.edit');

    // Templates Category
    Route::get('templates/category', TemplatesCategoryIndex::class)->name('templates.category');
    Route::get('templates/category/create', TemplatesCategoryCreate::class)->name('templates.category.create');
    Route::get('templates/category/{id}/edit', TemplatesCategoryEdit::class)->name('templates.category.edit');

    // Chat Templates
    Route::get('templates/chat', ChatTemplatesIndex::class)->name('chat.templates.index');
    Route::get('templates/chat/create', ChatTemplatesCreate::class)->name('chat.template.create');
    Route::get('templates/chat/{id}/edit', ChatTemplatesEdit::class)->name('chat.templates.edit');

    Route::get('transaction', TranscationIndex::class)->name('transaction.index');
    Route::get('user', UserIndex::class)->name('user.index');
    Route::get('profile/settings', SettingsProfileIndex::class)->name('profile.settings');
    Route::get('settings', SettingsIndex::class)->name('settings.index');
    Route::get('settings/hero', HeroSettings::class)->name('settings.hero');
    Route::get('settings/footer', FooterSettings::class)->name('settings.footer');
    Route::get('seo', SeoIndex::class)->name('seo.index');
    Route::get('page', PageIndex::class)->name('page.index');
    Route::get('page/create', PageCreate::class)->name('page.create');
    Route::get('page/edit/{id}', EditPage::class)->name('page.edit');
    Route::get('blog', BlogIndex::class)->name('blog.index');
    Route::get('blog/edit/{id}', BlogEdit::class)->name('blog.edit');
    Route::get('user/create', UserCreate::class)->name('user.create');
    Route::get('user/edit/{id}', EditUser::class)->name('user.edit');
    Route::get('blog/create', BlogCreate::class)->name('blog.create');
    Route::get('category', CategoryIndex::class)->name('category.index');
    Route::get('category/create', CategoryCreate::class)->name('category.create');
    Route::get('category/edit{id}', CategoryEdit::class)->name('category.edit');


    // Menu Settings
    Route::get('menu', MenuIndex::class)->name('menu.index');
    Route::get('menu/create', MenuCreate::class)->name('menu.create');
    Route::get('menu/edit/{id}', MenuEdit::class)->name('menu.edit');
    Route::get('menu/builder/{id}', MenuBuilder::class)->name('menu.builder');

    // getway Routes
    Route::get('gateway', GatewayIndex::class)->name('gateway.index');
    Route::get('gateway/create', GatewayCreate::class)->name('gateway.create');
    Route::get('gateway/edit/{id}', GatewayEdit::class)->name('gateway.edit');


    // Seo Routes
    Route::get('seo', SeoIndex::class)->name('seo.index');
    Route::get('seo/create', SeoCreate::class)->name('seo.create');
    Route::get('seo/edit/{id}', SeoEdit::class)->name('seo.edit');

    // Languages Routes
    Route::get('lang', LangIndex::class)->name('lang.index');
    Route::get('lang/create', LangCreate::class)->name('lang.create');
    Route::get('lang/{id}/edit', LangEdit::class)->name('lang.edit');
    Route::get('lang/cutomize/{id}', LangCustomize::class)->name('lang.customize');

    // Plan Routes
    Route::get('plan/index', PlanIndex::class)->name('plan.index');
    Route::get('plan/create', PlanCreate::class)->name('plan.create');
    Route::get('plan/edit/{id}', PlanEdit::class)->name('plan.edit');

app/Models/Getway.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Getway extends Model
{
    protected $fillable = [
        'name', 'logo', 'rate', 'charge', 'namespace', 'currency_name', 'image_accept', 'is_auto', 'test_mode', 'status', 'phone_required', 'instruction', 'data'
    ];

    use HasFactory;
}

app/Http/Livewire/Admin/Getway/Create.php
<?php

namespace App\Http\Livewire\Admin\Getway;

use App\Models\Getway;
use Illuminate\Support\Facades\Storage;
use Livewire\Component;
use Livewire\WithFileUploads;

class Create extends Component
{

    public $name, $logo, $rate, $charge, $currency_name, $image_accept = 0, $test_mode = 0, $status = 'approved', $phone_required = 0, $instruction;

    use WithFileUploads;

    public function store()
    {
        $this->validate([
            'name' => 'required',
            'logo' => 'image|required',
            'rate' => 'required|min:1',
            'charge' => 'required',
            'currency_name' => 'required',
            'status' => 'required',
            'instruction' => 'required'
        ]);

        if($this->logo)
        {
            $this->logo->store('getway','public');

            $logo = Storage::url('getway/'.$this->logo->hashName());
        }else{
            $logo = '';
        }

        Getway::create([
            'name' => $this->name,
            'logo' => $logo,
            'rate' => $this->rate,
            'charge' => $this->charge,
            'currency_name' => $this->currency_name,
            'namespace' => 'custom',
            'is_auto' => 0,
            'image_accept' => $this->image_accept,
            'test_mode' => $this->test_mode,
            'status' => $this->status,
            'phone_required' => $this->phone_required,
            'instruction' => $this->instruction,
            'data' => null
        ]);

        return redirect()->route('admin.gateway.index');
    }


    public function render()
    {
        return view('livewire.admin.getway.create');
    }
}

app/Http/Livewire/Admin/Getway/Edit.php
<?php

namespace App\Http\Livewire\Admin\Getway;

use Livewire\Component;
use App\Models\Getway;
use Illuminate\Support\Facades\Artisan;
use Livewire\WithFileUploads;
use Illuminate\Support\Facades\File;


class Edit extends Component
{

    public $getway, $name, $rate, $charge, $namespace, $currency_name, $image_accept, $is_auto, $test_mode, $status, $phone_required, $instruction, $data = [];

    use WithFileUploads;

    public $logo;

    public $fileUploadStatus = true;

    public function updatingLogo($value)
    {
        $this->fileUploadStatus = false;
    }

    public function updatedLogo()
    {
        $this->fileUploadStatus = false;

        if ($this->logo && $this->logo->isValid()) {
            $this->fileUploadStatus = true;
        } else {
            $this->fileUploadStatus = false;
        }
    }

    public function mount($id)
    {

        $this->getway = Getway::find($id);

        $this->fill([
            'name' => $this->getway->name,
            'rate' => $this->getway->rate,
            'charge' => $this->getway->charge,
            'test_mode' => $this->getway->test_mode,
        ]);

        if(json_decode($this->getway->data) != null)
        {
            foreach(json_decode($this->getway->data) as $key => $value) {
                $this->data[$key] = str_replace(' ', '', $value);
            }
        }

        $this->status = $this->getway->status;
    }

    public function update()
    {
        $this->validate([
            'name' => 'required|string|max:255',
            'logo' => 'nullable|image|max:255',
            'charge' => 'required|integer',
            'test_mode' => 'required|boolean',
            'status' => 'required|string|max:255',
            'data' => 'nullable'
        ]);

        if($this->logo)
        {
            $directory = public_path('uploads/getway');
            $tempPath = $this->logo->getRealPath();
            if (!File::exists($directory)) {
                File::makeDirectory($directory, 0755, true);
            }

            $extension = $this->logo->getClientOriginalExtension();
            $destinationPath = base_path().'/public/uploads/getway/'.$this->logo->hashName();
            rename($tempPath, $destinationPath);
            $logo = '/uploads/getway/'.$this->logo->hashName().'.'.$extension;
        }else {
            $logo = $this->getway->logo;
        }

        $this->getway->update([
            'name' => $this->name,
            'logo' => $logo,
            'charge' => $this->charge,
            'test_mode' => $this->test_mode,
            'status' => $this->status,
            'data' => json_encode($this->data)
        ]);

        foreach($this->data as $key => $value) {
            Artisan::call("env:set ".$key."='".str_replace(' ', '', $value)."'");
        }

        return redirect()->route('admin.gateway.index');
    }

    public function render()
    {
        return view('livewire.admin.getway.edit');
    }
}

app/Http/Livewire/Admin/Getway/Index.php
<?php

namespace App\Http\Livewire\Admin\Getway;

use App\Models\Getway;
use Livewire\Component;
use Livewire\WithPagination;

class Index extends Component
{

    use WithPagination;

    protected $paginationTheme = 'bootstrap';

    public $status;
    public $checklistId = [];
    public $search;
    public $filter_status;


    public function change_status()
    {
        if($this->status)
        {
            if($this->status == 'delete')
            {
                foreach($this->checklistId as $value)
                {
                    $getway = Getway::find($value);
                    if($getway->is_auto == 0)
                    {
                        $this->checklistId = [];
                        $getway->delete();
                    }else {
                        session()->flash('message', 'You can not delete auto getway');
                    }
                }
            }else{
                foreach($this->checklistId as $value)
                {
                    $page = Getway::find($value);
                    $page->status = $this->status;
                    $page->save();
                    $this->checklistId = [];
                }
            }
        }
    }

    public function render()
    {
        $searchTerm = '%'.$this->search.'%';
        if($this->filter_status)
        {
            if($this->filter_status == 'all')
            {
                $gateways = Getway::where([
                    ['name','like', $searchTerm]
                ])->latest()->paginate(20);
            }else{
                $gateways = Getway::where([
                    ['name','like', $searchTerm],
                    ['status', $this->filter_status]
                ])->latest()->paginate(20);
            }
            
        }else{
            $gateways = Getway::where([
                ['name','like', $searchTerm]
            ])->latest()->paginate(20);
        }

        return view('livewire.admin.getway.index',[
            'gateways' => $gateways
        ]);
    }
}

resources/views/livewire/admin/getway/index.blade.php
<div>
    @section('title', 'Payment Gateway')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
        <div class="d-block mb-4 mb-md-0">
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
                <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                    <li class="breadcrumb-item">
                        <a href="#">
                            <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                <path
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    stroke-width="2"
                                    d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
                                ></path>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">{{ env('APP_NAME') }}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ __('Gateway List') }}</li>
                </ol>
            </nav>
            <h2 class="h4">{{ __('Gateway List') }}</h2>
            <p class="mb-0">{{ __('Show All Gateway List') }}</p>
        </div>
    </div>
    <div>
        @if (session()->has('message'))
            <div class="alert alert-danger">
                {{ session('message') }}
            </div>
        @endif
    </div>
    <div class="table-settings mb-4">
        <div class="row justify-content-between align-items-center">
            <div class="col-9 col-lg-8 d-md-flex">
                <div class="input-group me-2 me-lg-3 fmxw-300">
                    <span class="input-group-text">
                        <svg class="icon icon-xs" x-description="Heroicon name: solid/search" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path>
                        </svg>
                    </span>
                    <input type="text" class="form-control" wire:model="search" placeholder="Search Getways" />
                </div>
                <select class="form-select fmxw-200 d-none d-md-inline" aria-label="Message select example 2" wire:model="filter_status">
                    <option value="all" selected="selected">{{ __('All') }}</option>
                    <option value="approved">{{ __('Active') }}</option>
                    <option value="pending">{{ __('Pending') }}</option>
                    <option value="darft">{{ __('Darft') }}</option>
                </select>
            </div>
            <div class="col-3 col-lg-4 d-flex justify-content-end">

            </div>
        </div>
    </div>
    <div class="card card-body shadow border-0 table-wrapper table-responsive">
        <form wire:submit.prevent="change_status">
            <div class="d-flex mb-3">
                <select class="form-select fmxw-200" aria-label="Message select example" wire:model="status">
                    <option selected="selected">{{ __('Select Action') }}</option>
                    <option value="pending">{{ __('Move To Pending') }}</option>
                    <option value="draft">{{ __('Move To Draft') }}</option>
                    <option value="approved">{{ __('Move To Active') }}</option>
                    <option value="delete">{{ __('Delete Permanently') }}</option>
                </select>
                <button type="submit" class="btn btn-sm px-3 btn-secondary ms-3">{{ __('Apply') }}</button>
            </div>
            <table class="table user-table table-hover align-items-center">
                <thead>
                    <tr>
                        <th class="border-bottom"></th>
                        <th class="border-bottom">{{ __('Image') }}</th>
                        <th class="border-bottom">{{ __('Name') }}</th>
                        <th class="border-bottom">{{ __('Charge') }}</th>
                        <th class="border-bottom">{{ __('Status') }}</th>
                        <th class="border-bottom">{{ __('Last Update') }}</th>
                        <th class="border-bottom">{{ __('Action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($gateways as $getway)
                    <tr>
                        <td>
                            <div class="form-check dashboard-check">
                                <input class="form-check-input" type="checkbox" wire:model="checklistId" value="{{ $getway->id }}" />
                            </div>
                        </td>
                        <td>
                            <img class="gateway-img" src="{{ $getway->logo }}" alt="">
                        </td>
                        <td>
                            {{ $getway->name }}
                        </td>
                        <td>
                            {{ $getway->charge }}
                        </td>
                        <td>
                            @if ($getway->status == 'approved')
                            <span class="fw-normal text-success">
                                {{ __('Active') }}
                            </span>
                            @elseif($getway->status  == 'pending')
                            <span class="fw-normal text-danger">
                                {{ __('Pending') }}
                            </span>
                            @elseif($getway->status == 'draft')
                            <span class="fw-normal text-danger">
                                {{ __('Draft') }}
                            </span>
                            @endif
                        </td>
                        <td><span class="fw-normal">{{ $getway->updated_at->toDateString() }}</span></td>
                        <td>
                            <a href="{{ route('admin.gateway.edit',$getway->id) }}" class="btn btn-sm btn-primary">{{ __('Edit') }}</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </form>
    </div>
</div>


<script src="{{ asset('assets/js/script.js') }}"></script>