routes/web.php
<?php

use App\Http\Controllers\Admin\InvoiceController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\User\AccountController;
use App\Http\Controllers\User\DashboardController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;
use App\Http\Livewire\Admin\Seo\Edit as SeoEdit;
use App\Http\Livewire\Admin\Blog\Edit as BlogEdit;
use App\Http\Livewire\Admin\Page\Edit as EditPage;
use App\Http\Livewire\Admin\Seo\Index as SeoIndex;
use App\Http\Livewire\Admin\User\Edit as EditUser;
use App\Http\Livewire\Admin\Blog\Index as BlogIndex;
use App\Http\Livewire\Admin\Page\Index as PageIndex;
use App\Http\Livewire\Admin\Seo\Create as SeoCreate;
use App\Http\Livewire\Admin\User\Index as UserIndex;
use App\Http\Livewire\Admin\Blog\Create as BlogCreate;
use App\Http\Livewire\Admin\Category\Index as CategoryIndex;
use App\Http\Livewire\Admin\Category\Create as CategoryCreate;
use App\Http\Livewire\Admin\Category\Edit as CategoryEdit;
use App\Http\Livewire\Admin\Page\Create as PageCreate;
use App\Http\Livewire\Admin\User\Create as UserCreate;
use App\Http\Livewire\Admin\Getway\Edit as GatewayEdit;
use App\Http\Livewire\Admin\Getway\Index as GatewayIndex;
use App\Http\Livewire\Admin\Settings\Hero as HeroSettings;
use App\Http\Livewire\Admin\Getway\Create as GatewayCreate;
use App\Http\Livewire\Admin\Settings\Index as SettingsIndex;
use App\Http\Livewire\Admin\Lang\Create as LangCreate;
use App\Http\Livewire\Admin\Lang\Customize as LangCustomize;
use App\Http\Livewire\Admin\Lang\Edit as LangEdit;
use App\Http\Livewire\Admin\Lang\Index as LangIndex;
use App\Http\Livewire\Admin\Menu\Builder as MenuBuilder;
use App\Http\Livewire\Admin\Menu\Create as MenuCreate;
use App\Http\Livewire\Admin\Menu\Edit as MenuEdit;
use App\Http\Livewire\Admin\Menu\Index as MenuIndex;
use App\Http\Livewire\Admin\Settings\Footer as FooterSettings;
use App\Http\Livewire\Admin\Transcation\Index as TranscationIndex;
use App\Http\Livewire\Admin\Settings\Profile\Index as SettingsProfileIndex;
use App\Http\Controllers\Admin\MenuOrderController;
use App\Http\Controllers\Auth\SocialiteController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\ChatbotShowController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PricingController;
use App\Http\Controllers\PrivacyController;
use App\Http\Controllers\User\AiChatsController;
use App\Http\Controllers\User\AiCodeController;
use App\Http\Controllers\User\AiImageController;
use App\Http\Controllers\User\AiSpeechToTextController;
use App\Http\Controllers\User\BillingController;
use App\Http\Controllers\User\DocumentController;
use App\Http\Controllers\User\PlanController;
use App\Http\Controllers\User\SettingsController;
use App\Http\Controllers\User\StripeController;
use App\Http\Controllers\User\SupportController;
use App\Http\Controllers\User\TemplatesController;
use App\Http\Livewire\Admin\Dashboard;
use App\Http\Livewire\Admin\Plan\Create as PlanCreate;
use App\Http\Livewire\Admin\Plan\Edit as PlanEdit;
use App\Http\Livewire\Admin\Plan\Index as PlanIndex;
use App\Http\Livewire\Admin\Settings\Affilate;
use App\Http\Livewire\Admin\Settings\Testimonial\Create as testimonialCreate;
use App\Http\Livewire\Admin\Settings\Testimonial\Edit as testimonialEdit;
use App\Http\Livewire\Admin\Settings\Testimonial\Index as testimonialIndex;
use App\Http\Livewire\Admin\Settings\Features\Create as FeaturesCreate;
use App\Http\Livewire\Admin\Settings\Features\Edit as FeaturesEdit;
use App\Http\Livewire\Admin\Settings\Features\Index as FeaturesIndex;
use App\Http\Livewire\Admin\Settings\Faq\Index as FAQIndex;
use App\Http\Livewire\Admin\Settings\Faq\Create as FAQCreate;
use App\Http\Livewire\Admin\Settings\Faq\Edit as FAQEdit;
use App\Http\Livewire\Admin\Settings\General;
use App\Http\Livewire\Admin\Settings\Invoice;
use App\Http\Livewire\Admin\Settings\OpenAi;
use App\Http\Livewire\Admin\Settings\PrivacyPolicy;
use App\Http\Livewire\Admin\Settings\Smtp;
use App\Http\Livewire\Admin\Settings\System\Index as SystemIndex;
use App\Http\Livewire\Admin\Support\Index as SupportIndex;
use App\Http\Livewire\Admin\Support\View as SupportView;
use App\Http\Livewire\Auth\Login;
use App\Http\Livewire\Admin\Emailtemplate\Edit as EmailTemplateEdit;
use App\Http\Livewire\Admin\Emailtemplate\Index as EmailTemplateIndex;
use App\Http\Livewire\Admin\Templates\BuildIn\Index as BuildInTemplatesIndex;
use App\Http\Livewire\Admin\Templates\BuildIn\Edit as BuildInTemplatesEdit;
use App\Http\Livewire\Admin\Templates\Category\Index as TemplatesCategoryIndex;
use App\Http\Livewire\Admin\Templates\Category\Create as TemplatesCategoryCreate;
use App\Http\Livewire\Admin\Templates\Category\Edit as TemplatesCategoryEdit;
use App\Http\Livewire\Admin\Templates\Chat\Create as ChatTemplatesCreate;
use App\Http\Livewire\Admin\Templates\Chat\Edit as ChatTemplatesEdit;
use App\Http\Livewire\Admin\Templates\Chat\Index as ChatTemplatesIndex;
use App\Http\Livewire\Admin\Templates\Custom\Index as CustomTemplatesIndex;
use App\Http\Livewire\Admin\Templates\Custom\Create as CustomTemplatesCreate;
use App\Http\Livewire\Admin\Templates\Custom\Edit as CustomTemplatesEdit;
use App\Http\Middleware\VerifyCsrfToken;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('admin/menu/order', [MenuOrderController::class, 'order'])->name('admin.menu.order');
/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('dashboard', Dashboard::class)->name('dashboard');

    // Built-in Templates
    Route::get('templates/all', BuildInTemplatesIndex::class)->name('buildin.templates');
    Route::get('templates/build-in/{id}/edit', BuildInTemplatesEdit::class)->name('buildin.templates.edit');

    // Custom Templates
    Route::get('templates/custom', CustomTemplatesIndex::class)->name('custom.templates');
    Route::get('templates/custom/create', CustomTemplatesCreate::class)->name('custom.templates.create');
    Route::get('templates/custom/{id}/edit', CustomTemplatesEdit::class)->name('custom.templates.edit');

    // Templates Category
    Route::get('templates/category', TemplatesCategoryIndex::class)->name('templates.category');
    Route::get('templates/category/create', TemplatesCategoryCreate::class)->name('templates.category.create');
    Route::get('templates/category/{id}/edit', TemplatesCategoryEdit::class)->name('templates.category.edit');

    // Chat Templates
    Route::get('templates/chat', ChatTemplatesIndex::class)->name('chat.templates.index');
    Route::get('templates/chat/create', ChatTemplatesCreate::class)->name('chat.template.create');
    Route::get('templates/chat/{id}/edit', ChatTemplatesEdit::class)->name('chat.templates.edit');

    Route::get('transaction', TranscationIndex::class)->name('transaction.index');
    Route::get('user', UserIndex::class)->name('user.index');
    Route::get('profile/settings', SettingsProfileIndex::class)->name('profile.settings');
    Route::get('settings', SettingsIndex::class)->name('settings.index');
    Route::get('settings/hero', HeroSettings::class)->name('settings.hero');
    Route::get('settings/footer', FooterSettings::class)->name('settings.footer');
    Route::get('seo', SeoIndex::class)->name('seo.index');
    Route::get('page', PageIndex::class)->name('page.index');
    Route::get('page/create', PageCreate::class)->name('page.create');
    Route::get('page/edit/{id}', EditPage::class)->name('page.edit');
    Route::get('blog', BlogIndex::class)->name('blog.index');
    Route::get('blog/edit/{id}', BlogEdit::class)->name('blog.edit');
    Route::get('user/create', UserCreate::class)->name('user.create');
    Route::get('user/edit/{id}', EditUser::class)->name('user.edit');
    Route::get('blog/create', BlogCreate::class)->name('blog.create');
    Route::get('category', CategoryIndex::class)->name('category.index');
    Route::get('category/create', CategoryCreate::class)->name('category.create');
    Route::get('category/edit{id}', CategoryEdit::class)->name('category.edit');


    // Menu Settings
    Route::get('menu', MenuIndex::class)->name('menu.index');
    Route::get('menu/create', MenuCreate::class)->name('menu.create');
    Route::get('menu/edit/{id}', MenuEdit::class)->name('menu.edit');
    Route::get('menu/builder/{id}', MenuBuilder::class)->name('menu.builder');

    // getway Routes
    Route::get('gateway', GatewayIndex::class)->name('gateway.index');
    Route::get('gateway/create', GatewayCreate::class)->name('gateway.create');
    Route::get('gateway/edit/{id}', GatewayEdit::class)->name('gateway.edit');


    // Seo Routes
    Route::get('seo', SeoIndex::class)->name('seo.index');
    Route::get('seo/create', SeoCreate::class)->name('seo.create');
    Route::get('seo/edit/{id}', SeoEdit::class)->name('seo.edit');

    // Languages Routes
    Route::get('lang', LangIndex::class)->name('lang.index');
    Route::get('lang/create', LangCreate::class)->name('lang.create');
    Route::get('lang/{id}/edit', LangEdit::class)->name('lang.edit');
    Route::get('lang/cutomize/{id}', LangCustomize::class)->name('lang.customize');

    // Plan Routes
    Route::get('plan/index', PlanIndex::class)->name('plan.index');
    Route::get('plan/create', PlanCreate::class)->name('plan.create');
    Route::get('plan/edit/{id}', PlanEdit::class)->name('plan.edit');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function chatbot(){
        return $this->hasMany('App\Models\Chatbot');
    }
}

app/Http/Controllers/User/AccountController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Option;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Auth;
use Hash;
use Illuminate\Support\Str;


class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $settings = json_decode(Option::where('key', 'site_settings')->first()->value);
        $user = Auth::User();
        return Inertia::render('User/Account', [
            'user' => $user,
            'logo' => $settings->site_logo
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = Auth::User();

        if($request->hasFile('profile'))
        {
            $request->validate([
                'profile' => 'required|image'
            ]);

            $image = $request->file('profile');
            $imageName = time() .'_'. Str::random(10) . '.' . $image->getClientOriginalExtension();
            $image->move(public_path('profile/img'), $imageName);
            $imageName = '/profile/img/'.$imageName;
        }else{
            $imageName = $user->profile;
        }

        $user->name = $request->name;
        $user->email = $request->email;
        $user->profile = $imageName;


        if($request->previousPassword)
        {
            if(Hash::check($request->previousPassword, $user->password)){

                $user->password = Hash::make($request->password);
                $user->save();
                return 'success';

            }else{
                return response()->json(['currentPassword' => 'The Current Password Is Invalid'], 401);
            }
        }

        $user->save();
        return 'success';

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/DocumentController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Document;
use App\Models\Option;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Inertia\Inertia;

class DocumentController extends Controller
{

    public function index()
    {
        $documentTypes = ['aiwrite', 'aiCode', 'aiSpeechToText'];
        $documents = Document::with('template')->whereIn('type', $documentTypes)
            ->where('user_id', Auth::User()->id)
            ->latest()
            ->paginate(20);

        $settings = json_decode(Option::where('key', 'site_settings')->first()->value);

        return Inertia::render('User/Document', [
            'logo' => $settings->site_logo,
            'documents' => $documents,
            'pagination' => [
                'currentPage' => $documents->currentPage(),
                'lastPage' => $documents->lastPage(),
                'prev_page_url' => $documents->previousPageUrl(),
                'next_page_url' => $documents->nextPageUrl(),
                'form' => $documents->firstItem(),
                'to' => $documents->lastItem(),
                'total' => $documents->total(),
                'per_page' => $documents->perPage()
            ],
        ]);
    }



    public function rename(Request $request)
    {
        $document = Document::findOrFail($request->id);
        if(!$document)
        {
            return abort(404);
        }

        $document->title = $request->title;
        $document->save();

        return response()->json('Saved');
    }

    public function show($slug)
    {
        $document = Document::with('template')->where('slug', $slug)->first();
        $settings = json_decode(Option::where('key', 'site_settings')->first()->value);

        return Inertia::render('User/DocumentShow', [
            'logo' => $settings->site_logo,
            'documentInfo' => $document
        ]);
    }

    public function update(Request $request)
    {
        $document = Document::findOrFail($request->id);
        if(!$document)
        {
            return abort(404);
        }

        $document->data = $request->data;
        $document->save();

        return response()->json('Saved');
    }

    public function bookmark(Request $request)
    {
        $document = Document::findOrFail($request->id);
        if($document->is_bookmark === 1)
        {
            $document->is_bookmark = 0;
        }else {
            $document->is_bookmark = 1;
        }
        $document->save();

        return response()->json('Bookmarked');
    }

    public function delete(Request $request)
    {
        Document::find($request->id)->delete();
        return response()->json('Deleted');
    }

}

app/Http/Controllers/User/SettingsController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Chatbot;
use App\Models\Option;
use App\Models\Plan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Inertia\Inertia;

class SettingsController extends Controller
{
    public function index(Request $request)
    {
        $appName = env('APP_NAME');
        $user = Auth::User();
        $plan = Plan::where('id', $user->plan_id)->first();

        $settings = json_decode(Option::where('key', 'site_settings')->first()->value);

        return Inertia::render('User/Settings', [
            'appName' => $appName,
            'planName' => $plan->name,
            'user' => $user,
            'logo' => $settings->site_logo
        ]);
    }

    public function information()
    {
        $user = Auth::User();
        $settings = json_decode(Option::where('key', 'site_settings')->first()->value);

        return Inertia::render('User/SettingsUpdate', [
            'user' => $user,
            'logo' => $settings->site_logo
        ]);
    }
}

resources/views/livewire/admin/user/index.blade.php
<div>
    @section('title', 'Manage User')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
        <div class="d-block mb-4 mb-md-0">
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
                <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                    <li class="breadcrumb-item">
                        <a href="#">
                            <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                <path
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    stroke-width="2"
                                    d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
                                ></path>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">{{ env('APP_NAME') }}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ __('User List') }}</li>
                </ol>
            </nav>
            <h2 class="h4">{{ __('User List') }}</h2>
            <p class="mb-0">{{ __('Show All User List') }}</p>
        </div>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ route('admin.user.create') }}" class="btn btn-sm btn-gray-800 d-inline-flex align-items-center">
                <svg class="icon icon-xs me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                </svg>
                {{ __('New User') }}
            </a>
        </div>
    </div>
    <div class="table-settings mb-4">
        <div class="row justify-content-between align-items-center">
            <div class="col-9 col-lg-8 d-md-flex">
                <div class="input-group me-2 me-lg-3 fmxw-300">
                    <span class="input-group-text">
                        <svg class="icon icon-xs" x-description="Heroicon name: solid/search" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path>
                        </svg>
                    </span>
                    <input type="text" class="form-control" wire:model="search" placeholder="Search Users" />
                </div>
                <select class="form-select fmxw-200 d-none d-md-inline" aria-label="Message select example 2" wire:model="filter_status">
                    <option value="all" selected="selected">{{ __('All') }}</option>
                    <option value="active">{{ __('Active') }}</option>
                    <option value="pending">{{ __('Pending') }}</option>
                    <option value="darft">{{ __('Darft') }}</option>
                </select>
            </div>
            <div class="col-3 col-lg-4 d-flex justify-content-end">

            </div>
        </div>
    </div>
    <div class="card card-body shadow border-0 table-wrapper table-responsive">
        <form wire:submit.prevent="change_status">
            <div class="d-flex mb-3">
                <select class="form-select fmxw-200" aria-label="Message select example" wire:model="status">
                    <option selected="selected">{{ __('Select Action') }}</option>
                    <option value="pending">{{ __('Move To Pending') }}</option>
                    <option value="draft">{{ __('Move To Draft') }}</option>
                    <option value="active">{{ __('Move To Active') }}</option>
                    <option value="delete">{{ __('Delete Permanently') }}</option>
                </select>
                <button type="submit" class="btn btn-sm px-3 btn-secondary ms-3">{{ __('Apply') }}</button>
            </div>
            <table class="table user-table table-hover align-items-center">
                <thead>
                    <tr>
                        <th class="border-bottom">

                        </th>
                        <th class="border-bottom">{{ __('Name') }}</th>
                        <th class="border-bottom">{{ __('Email') }}</th>
                        <th class="border-bottom">{{ __('Date Created') }}</th>
                        <th class="border-bottom">{{ __('Status') }}</th>
                        <th class="border-bottom">{{ __('Action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($users as $user)
                    @if ($user->user_type != 'admin')
                    <tr>
                        <td>
                            <div class="form-check dashboard-check">
                                <input class="form-check-input" type="checkbox" wire:model="checklistId" value="{{ $user->id }}" />
                            </div>
                        </td>
                        <td>
                            <span class="fw-bold">{{ $user->name }}</span>
                        </td>
                        <td><span class="fw-blod">{{ $user->email }}</span></td>
                        <td><span class="fw-normal">{{ $user->created_at->toDateString()}}</span></td>
                        <td>
                            @if ($user->status == 'active')
                            <span class="fw-normal text-success">
                                {{ __('Active') }}
                            </span>
                            @elseif($user->status == 'pending')
                            <span class="fw-normal text-danger">
                                {{ __('Pending') }}
                            </span>
                            @elseif($user->status == 'draft')
                            <span class="fw-normal text-danger">
                                {{ __('Draft') }}
                            </span>
                            @endif
                        </td>
                        <td>
                            <div class="btn-group text-center">
                                <button class="btn btn-link text-dark dropdown-toggle dropdown-toggle-split m-0 p-0" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"></path>
                                    </svg>
                                </button>
                                <div class="dropdown-menu dashboard-dropdown dropdown-menu-start mt-2 py-1" >
                                    <a class="dropdown-item d-flex align-items-center" href="{{ route('admin.user.edit',$user->id) }}">
                                        <svg class="mr-3" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="18" height="18"><path fill="none" d="M0 0h24v24H0z"/><path d="M16.757 3l-2 2H5v14h14V9.243l2-2V20a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h12.757zm3.728-.9L21.9 3.516l-9.192 9.192-1.412.003-.002-1.417L20.485 2.1z" fill="rgba(156,163,175,1)"/></svg>
                                        {{ __('Edit User') }}
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endif
                    @endforeach
                </tbody>
            </table>
        </form>
        <div class="card-footer px-3 border-0 d-flex flex-column flex-lg-row align-items-center justify-content-end">
            {{ $users->links() }}
        </div>
    </div>
</div>


<script src="{{ asset('assets/js/script.js') }}"></script>